config/routes.rb
LancingMarket::Application.routes.draw do
  resources :projects do
    resources :milestones
  end
  
  get "sessions/new"

  match 'login' => 'sessions#new', :as => "login"
  match 'logout' => 'sessions#destroy', :as => "logout"
  match 'register' => 'contractants#new', :as => "register"

  resources :contractants
  resources :sessions

  #Projects routing

  match "/projects/new" => "Projects#create"
  match "/projects/list" => "Projects#all"
  match "/projects/:id" => "Projects#show"

  root :to => 'Home#index'
end

app/models/contractant.rb
class Contractant < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation
  attr_accessor :password
  has_many :project
  accepts_nested_attributes_for :project

  before_save :encrypt_password

  validates_presence_of :username
  validates_uniqueness_of :username
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create, :message => "can't be blank"

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(username, password)
    user = find_by_username(username)
    return user if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  end
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  attr_accessible :description, :id, :import, :number
  belongs_to :project
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :id, :name, :version
  belongs_to :contractant
  has_many :milestone

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  
  private

  def current_user
  	begin
  		@current_user ||= Contractant.find(session[:user_id]) if session[:user_id]
  	rescue ActiveRecord::RecordNotFound  => e
  		@current_user = nil
  	end
  end
end

app/controllers/contractants_controller.rb
class ContractantsController < ApplicationController

  def login
  end


  # GET /contractants
  # GET /contractants.json
  def index
    @contractants = Contractant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contractants }
    end
  end

  # GET /contractants/1
  # GET /contractants/1.json
  def show
    @contractant = Contractant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contractant }
    end
  end

  def new
    @contractant = Contractant.new
  end
  
  def create
    @contractant = Contractant.new(params[:contractant])
    if @contractant.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  # GET /contractants/1/edit
  def edit
    @contractant = Contractant.find(params[:id])
  end

  # POST /contractants
  # POST /contractants.json
  # def create
  #   @contractant = Contractant.new(params[:contractant])

  #   respond_to do |format|
  #     if @contractant.save
  #       format.html { redirect_to @contractant, notice: 'Contractant was successfully created.' }
  #       format.json { render json: @contractant, status: :created, location: @contractant }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @contractant.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PUT /contractants/1
  # PUT /contractants/1.json
  def update
    @contractant = Contractant.find(params[:id])

    respond_to do |format|
      if @contractant.update_attributes(params[:contractant])
        format.html { redirect_to @contractant, notice: 'Contractant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contractant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contractants/1
  # DELETE /contractants/1.json
  def destroy
    @contractant = Contractant.find(params[:id])
    @contractant.destroy

    respond_to do |format|
      format.html { redirect_to contractants_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  # GET /milestones
  # GET /milestones.json
  def index
    project = Project.find(params[:project_id])
    @milestones = project.milestone.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @milestones }
    end
  end

  # GET /milestones/1
  # GET /milestones/1.json
  def show
    @milestone = Milestone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @milestone }
    end
  end

  # GET /milestones/new
  # GET /milestones/new.json
  def new
    @milestone = Milestone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @milestone }
    end
  end

  # GET /milestones/1/edit
  def edit
    @milestone = Milestone.find(params[:id])
  end

  # POST /milestones
  # POST /milestones.json
  def create
    @milestone = Milestone.new(params[:milestone])

    respond_to do |format|
      if @milestone.save
        format.html { redirect_to @milestone, notice: 'Milestone was successfully created.' }
        format.json { render json: @milestone, status: :created, location: @milestone }
      else
        format.html { render action: "new" }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /milestones/1
  # PUT /milestones/1.json
  def update
    @milestone = Milestone.find(params[:id])

    respond_to do |format|
      if @milestone.update_attributes(params[:milestone])
        format.html { redirect_to @milestone, notice: 'Milestone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milestones/1
  # DELETE /milestones/1.json
  def destroy
    @milestone = Milestone.find(params[:id])
    @milestone.destroy

    respond_to do |format|
      format.html { redirect_to milestones_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  def index
    @projects = current_user.project.all
  end
  
  def new
  	raise ActionController::RoutingError.new('Not found') unless current_user
  	@project = current_user.project.build
  	@project.milestone.build
  end

  def create
    @project = current_user.project.build(params[:project])
    params[:milestone].each_value { |milestone| 
    	@project.milestone.build(milestone)
    }
    if @project.save
      redirect_to "/projects/#{@project.id}", :notice => "Projecte afegit correctament!"
    else
      render "new"
    end  end

  def all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end
	
  def create
  	user = Contractant.authenticate(params[:username], params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to root_url, :notice => "Logged in!"
  	else
  		flash.now.alert = "Nom d'usuari o contrasenya invalids"
  		render "new"
  	end
  end

  def destroy
		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contractants_helper.rb
module ContractantsHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/application/_header.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
      <meta charset="utf-8">
      <title>Lancing Market</title>
      <meta name="description" content="">
      <meta name="author" content="Grup 2">

      <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
      <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

      <!-- Styles -->
      <%= stylesheet_link_tag '/stylesheets/bootstrap' %>

      <!-- Fav and touch icons -->
      
      <!-- incloure l'arxiu de utils javascript -->
      <%= javascript_include_tag '/javascripts/utils', '/javascripts/bootstrap', '/javascripts/bootstrap-alert' %> 

      <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
      <!-- Fav and touch icons -->
  </head>
  <body>
    <nav class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">Lancing Market</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li>
                <%= link_to "Inici", root_url %>
              </li>
              <li>
                <% if current_user %>
                  <%= link_to "Benvingut, #{current_user.username}", {:controller => :contractants, :action => :show, :id => current_user.id } %>
                <% else %>
                  <%= link_to "Registrar-se", {:controller => :contractants, :action => "new"}%>
                <% end %>
              </li>
              <li>
                <% if current_user %>
                  <%= link_to "Sortir", logout_path %>
                <% else %>
                  <%= link_to "Entrar", "/login" %>
                <% end %>
              </li>
              <li>
                <% if current_user %>
                  <%= link_to "Afegir projecte", {:controller => :projects, :action => "new"} %>
                <% end %>
              </li>
            </ul>
            <form class="navbar-search pull-left" action>
              <input type="text" class="search-query span2" placeholder="Cerca">
            </form>
          </div>
        </div>
      </div>
    </nav>

app/views/contractants/_form.html.erb
    <section class="container">
      <section class="center span8">
        <h1>Crea un usuari</h1>
        <div class="alert alert-block alert-success">
          <p>Ja ets usuari? Entra emprant la barra de login superior, o prement aquest botó:</p>
          <p>
            <%= link_to "Login", "/login", :class => "btn" %>
          </p>
        </div>  
        <%= form_for(@contractant, :html => {:class => "well form-vertical"}) do |f| %>
          <% if @contractant.errors.any? %>
              <h3><%= pluralize(@contractant.errors.count, "error") %> prohibited this contractant from being saved:</h2>

              <ul>
              <% @contractant.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
          <% end %>

            <%= f.label "Nom:" %>
            <%= f.text_field :username, :class=>"span3", :placeholder=>"Entra el teu nom complet" %>

            <%= f.label "Contrasenya:" %>
            <%= f.password_field :password, :class=>"span3", :placeholder=>"Contrasenya" %>

            <%= f.label "Confirmació de contrasenya:" %>
            <%= f.password_field :password_confirmation, :class=>"span3", :placeholder=>"Confirma la teva contrasenya" %>

          <div class="actions">
            <%= f.submit "Envia", :class => "btn btn-success", :onClick =>"parent.location='home_contractista.html'"%>
            <button type="reset" value="Reset" class="btn">Reset</button>
          </div>
        <% end %>
      </section>
    </section>
  </body>
<script>
  $(document).ready(function() {
    // inserta_head_home();
    $(".nav-collapse .nav li:first").removeClass("active");
    $(".nav-collapse .nav li:eq(1)").addClass("active");
    inserta_footer();
  });
</script>
</html>

app/views/contractants/edit.html.erb
<h1>Editing contractant</h1>

<%= render 'form' %>

<%= link_to 'Show', @contractant %> |
<%= link_to 'Back', contractants_path %>

app/views/contractants/index.html.erb
<h1>Listing contractants</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contractants.each do |contractant| %>
  <tr>
    <td><%= contractant.username %></td>
    <td><%= contractant.password %></td>
    <td><%= link_to 'Show', contractant %></td>
    <td><%= link_to 'Edit', edit_contractant_path(contractant) %></td>
    <td><%= link_to 'Destroy', contractant, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contractant', new_contractant_path %>

app/views/contractants/new.html.erb
<%= render 'form' %>

app/views/contractants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @contractant.username %>
</p>

<p>
  <b>Password:</b>
  <%= @contractant.password %>
</p>


<%= link_to 'Edit', edit_contractant_path(@contractant) %> |
<%= link_to 'Back', contractants_path %>

app/views/home/index.html.erb
		<section class="container">

			<section class="hero-unit">
				<h1>Benvingut a Lancing market!</h1>
				<br>
				<br>
  				<p>This is a mock-up wireframe yet. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  				tempor incididunt ut labore et dolore magna aliqua.</p>
  				<br>
				<br>
				<p>
					<a class="btn btn-primary btn-large">
				    	Pricing &amp; Terms
				    </a>
				</p>
			</section>
		</section>
</body>
<script>
	$(document).ready(function() {
		inserta_footer();
	});
</script>

app/views/layouts/application.html.erb
<%= render 'header' %>
	
<%= yield %>

</body>
</html>

app/views/milestones/_form.html.erb
<%= form_for(@milestone) do |f| %>
  <% if @milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
      <% @milestone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :import %><br />
    <%= f.text_field :import %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/milestones/edit.html.erb
<h1>Editing milestone</h1>

<%= render 'form' %>

<%= link_to 'Show', @milestone %> |
<%= link_to 'Back', milestones_path %>

app/views/milestones/index.html.erb
<h1>Listing milestones</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Number</th>
    <th>Import</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @milestones.each do |milestone| %>
  <tr>
    <td><%= milestone.id %></td>
    <td><%= milestone.number %></td>
    <td><%= milestone.import %></td>
    <td><%= milestone.description %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Milestone', new_project_milestone_path %>

app/views/milestones/new.html.erb
<h1>New milestone</h1>

<%= render 'form' %>

<%= link_to 'Back', milestones_path %>

app/views/milestones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @milestone.id %>
</p>

<p>
  <b>Number:</b>
  <%= @milestone.number %>
</p>

<p>
  <b>Import:</b>
  <%= @milestone.import %>
</p>

<p>
  <b>Description:</b>
  <%= @milestone.description %>
</p>


<%= link_to 'Edit', edit_milestone_path(@milestone) %> |
<%= link_to 'Back', milestones_path %>

app/views/projects/_form.html.erb
<%= form_for(@project, :html => {:class => "well form-vertical"}) do |f| %>
          <%= f.label "Nom:" %>
          <%= f.text_field :name, :class => "span3", :placeholder => "Escriu un nom pel projecte" %>
          <span class="help-inline">Només caràcters alfanumèrics permesos!</span>
          
          <%= f.label "Versió:" %>
          <%= f.text_field :version, :class => "span3", :placeholder => "Versió inicial" %>
          <span class="help-inline">Només caràcters alfanumèrics permesos!</span>

          <%= f.label "Descripció:" %>
          <%= f.text_area :description, :class => "input-xxlarge", :rows => "3", :id => "textarea", :placeholder => "Escriu una descripció detallada del projecte" %>
          <span class="help-inline">Només caràcters alfanumèrics permesos!</span>
          
          <br>
          <br>
          <div id="milestones">
            <h4>Fites</h4>
              <% @project.milestone.each_with_index do |milestone, index| %>
                <%= render :partial => 'form_milestone', :locals => { :milestone => milestone, :index => index } %>
            <%end%>
          </div>
              <br>
              <br>
              <div style="float:right;">
                <label>Import total del projecte</label>
                <input id="counter" type="text" class="span3" placeholder="Quantitat total" readonly="readonly">
              </div>
              <a id="add_milestone" class="btn btn-warning" href="#"><i class="icon-plus icon-white"></i> Afegir fita</a>
              <br>
              <br>
              <br>
              <br>
          <div class="actions">
            <%= f.submit "Envia", :class => "btn btn-success", :onClick =>"parent.location='my_projects_contractant.html'"%>
            <button type="reset" value="Reset" class="btn">Reset</button>
          </div>
        <% end %>

app/views/projects/_form_milestone.html.erb
<div id="milestone_<%= index %>">
   <%= fields_for "milestone[#{index}]", milestone do |m| %>
     <br>
     <%= m.label "Numero:" %>
     <%= m.number_field :number, :class => "span3", :placeholder => "Entra un nombre per a la fita" %>
     <span class="help-inline">Només caràcters numèrics permesos!</span>

     <%= m.label "Import:" %>
     <%= m.number_field :import, :class => "import span3", :placeholder => "Entra un import per a la fita", :onchange => "refresh_counter();"%>
     <span class="help-inline">Només caràcters numèrics permesos!</span>

     <%= m.label "Descripció:" %>
     <%= m.text_area :description, :class => "input-xxlarge", :rows => "3", :id => "textarea", :placeholder => "Escriu una descripció detallada de la fita" %>
     <span class="help-inline">Només caràcters alfanumèrics permesos!</span>
     <br>
     <br>
     <a class="btn btn-danger remove_milestone" href="#" onclick="remove_milestone('milestone_<%= index %>'); return false;"><i class="icon-trash icon-white"></i> Eliminar aquesta fita</a>
     <br>
   <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Version</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.id %></td>
    <td><%= project.name %></td>
    <td><%= project.version %></td>
    <td><%= project.description %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
	<section class="container">
		<section class="center span8">
			<h1>Afegir un projecte</h1>
			<br>
			<br>
			<%= render 'form' %>
		</section>
	</section>
</body>
<footer>
</footer>
<script>
		indice = 1;

		function remove_milestone(id) {
			$('#'+id).remove();
			refresh_counter();
		}

		function refresh_counter() {
			var sum = 0;
			$(".import").each(function() {
				if( (!isNaN( $(this).val() ) ) && ( $(this).val() != null ) && ( $(this).val() != "" ) ) sum += parseInt($(this).val());
			});
			$("#counter").val(sum);
		}

		$("#add_milestone").click(function(event){
			indice += 1;
			event.preventDefault();
			$("#milestones").append('<div id="milestone_'+indice+'"><br><label for="milestone_'+indice+'_Numero:">Numero:</label><input class="span3" id="milestone_'+indice+'_number" name="milestone['+indice+'][number]" placeholder="Entra un nombre per a la fita" type="number"><span class="help-inline">Només caràcters numèrics permesos!</span><label for="milestone_'+indice+'_Import:">Import:</label><input class="import span3" id="milestone_'+indice+'_import" name="milestone['+indice+'][import]" onchange="refresh_counter();" placeholder="Entra un import per a la fita" type="number"><span class="help-inline">Només caràcters numèrics permesos!</span><label for="milestone_'+indice+'_Descripció:">Descripció:</label><textarea class="input-xxlarge" cols="4'+indice+'" id="textarea" name="milestone['+indice+'][description]" placeholder="Escriu una descripció detallada de la fita" rows="3"></textarea><span class="help-inline">Només caràcters alfanumèrics permesos!</span><br><br><a class="btn btn-danger remove_milestone" href="#" onclick="remove_milestone(\'milestone_'+indice+'\'); return false;"><i class="icon-trash icon-white"></i> Eliminar aquesta fita</a><br></div>');
		});

		$(document).ready(function(){
				inserta_footer();
		});
		
	
</script>
</html>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @project.id %>
</p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Version:</b>
  <%= @project.version %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Fites:</b>
	<ul>
	  <%= @project.milestone.each do |milestone| %>
			<li>
					<p>Number: <%= milestone.number %></p>
					<p>Import: <%= milestone.import %></p>
					<p>Description: <%= milestone.description %></p>
			</li>
		<% end %>
	</ul>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>